title: "International Research Project SINFIN"
description: "Systèmes, vérIfication, iNformatique Fondamentale, logIque, laNgages"
url: "https://irp-sinfin.github.io"
baseurl: ""


remote_theme: jekyll/minima

header_pages:
  - index.md
  - history.md
  - co-publications.md
  - bilateral-projects.md
  - organization.md   
  - research.md

paginate: 10
paginate_path: "/page:num/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
